kuasar-io/kuasar

vmm/sandbox/src/stratovirt/config.rs
vmm/sandbox/src/stratovirt/devices/block.rs
vmm/sandbox/src/stratovirt/factory.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/vm.rs

After this , we support using kuasar to boot startovirt VM with **block image as rootfs**.
Specifify image_path in config file to try it~

support start startovirt vm with image

---

README.md
docs/vmm/how-to-run-kuasar-with-isulad-and-stratovirt.md
vmm/scripts/image/centos/build.sh
vmm/scripts/image/centos/build_rootfs.sh

fix the issue #25 
1. fix the build rootfs container left problem when build-script return error
2. install golang package directly from [golang](https://go.dev/dl/)
3. format the shell scripts by `shfmt` tool.

[vmm]: fix initrd building error in aarch64 enviroment

---

vmm/scripts/image/centos/build_rootfs.sh

reason: use cert_file_path variable to refer the cert file in the build container instead of a contant value.

[vmm]: fix cert_file_path variable in the build scripts

---

vmm/common/src/lib.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/container/handler/append.rs
vmm/sandbox/src/container/handler/spec.rs
vmm/sandbox/src/qemu/factory.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/storage/mod.rs
vmm/sandbox/src/stratovirt/factory.rs
vmm/sandbox/src/stratovirt/mod.rs

1. As we just need to mount guest needed directory and files to guest, other files like console sock and sandbox.json should not be mounted into guest, so we create a shared directory to store those needed by guest and mount it only.
after optimizing:
2. create bundle directory earlier
Before this, container bundle directory was initialized and created in spec handler, but it was used by storage handler and io handler which before spec handler, bundle directory was still "" in storage handler and io handler, which caused files were created under "/". So we should initialize and create bundle directory in metadata add handler which is before all other ones.

optimize sandbox directory structure

---

vmm/sandbox/config_clh.toml
vmm/sandbox/config_stratovirt.toml
vmm/sandbox/src/kata_config.rs
vmm/sandbox/src/main.rs
vmm/sandbox/src/sandbox.rs

fix #35
reason: Add 'sandbox.log_level' field in the config file to support configure the vmm-sandboxer process log level.

[vmm]: support configure log_level in the config file

---

vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/main.rs
vmm/sandbox/src/qemu/config.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/config.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/vm.rs

Recover stratovirt or qemu sandbox information when vmm-sandboxer restarting to make sure sandbox started before could be controlled.

vmm: support stratovirt and qemu sandbox recovery

---

Makefile
docs/vmm/README.md
vmm/service/kuasar-vmm
vmm/service/kuasar-vmm.service

Fix: #4
reason: add vmm-sandboxer as a systemd service

[vmm]: add vmm-sandboxer as a systemd service

---

.github/workflows/ci.yml
vmm/sandbox/Cargo.lock
vmm/sandbox/Cargo.toml
vmm/sandbox/src/cgroup.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/main.rs
vmm/sandbox/src/qemu/config.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/stratovirt/qmp.rs
vmm/sandbox/src/utils.rs
vmm/sandbox/src/vm.rs

fix: #51
reason:
1. limit the vm process resource usage in the specified cgroup dir
2. support pod_overhead conception actually, which limits the non-vcpu type threads of vm process into pod_overhead cgroup dir and set the pod_overhead resources limit in this cgroup dir.

[vmm]: support sandbox cgroup management in the host

---

.github/workflows/ci.yml
wasm/Cargo.lock
wasm/Cargo.toml
wasm/deny.toml
wasm/src/main.rs
wasm/src/sandbox.rs
wasm/src/utils.rs
wasm/src/wasmedge.rs
wasm/src/wasmtime.rs

support wasmtime as the wasm runtime for webassembly sandbox.
it use async feature of wasmtime and launch the instance inside the process, without forking a new process.
and the limit of memory is supported by wasmtime ResourceLimiter.
the cpu limitation of wasmtime is made by a "fuel" machanism and I am not sure how to make it follow the cpu quota limitation of containers. so cpu limitation is still not supported.

wasm: add support of wasmtime for webassembly sandbox

---

docs/vmm/README.md
vmm/task/src/config.rs
vmm/task/src/main.rs

Before this we reuse "task.log_level" to determine whether listening debug console port, which is not so good, individually specifying task.debug to enable debug_console is needed.

vmm-task:individually specify task.debug to enable debug_console

---

docs/vmm/README.md
docs/vmm/how-to-run-kuasar-with-isulad-and-stratovirt.md

Due to the code refact and Kuasar is about to release by openEuler 23.09, update the docs of iSulad+Kuasar+StratoVirt for easy reading.

doc: update vmm docs for isulad+stratovirt

---

Makefile
quark/service/kuasar-quark.service

The kuasar-quark process should be running as a systemd service.

quark: add kuasar-quark systemd service

---

vmm/task/src/task.rs

Fix: https://github.com/kuasar-io/kuasar/issues/76

vmm task: should kill all process even no bundle

---

vmm/sandbox/src/stratovirt/config.rs
vmm/sandbox/src/stratovirt/factory.rs

Use config "debug" in stratovirt config file to enable debug_console and dump stratovirt log.

vmm: use config debug to enable debug_console and stratovirt log

---

vmm/sandbox/src/utils.rs

Fix the division by zero bug when calculating CPU quota

[vmm]:Fix the division by zero bug when calculating CPU quota

---

wasm/src/main.rs

Remove SIGTERM and SIGINT signal handling. Shutdown when received them.

[wasm] remove SIGTERM and SIGINT signal handling

---

quark/src/sandbox.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/mod.rs
wasm/src/sandbox.rs

Fix lint check warning introduced after upgrading to Rust clippy 0.1.72

ci: fix cargo clippy warnings

---

quark/src/sandbox.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/mod.rs
wasm/Cargo.lock
wasm/Cargo.toml
wasm/src/sandbox.rs
wasm/src/utils.rs
wasm/src/wasmedge.rs
wasm/src/wasmtime.rs

Add wasmEdge container process to cgroup, follow up #74

wasm: add wasmEdge container process to cgroup

---

wasm/src/wasmedge.rs

wasm: collect cgroup metrics as stats in wasmedge

---

Makefile
wasm/service/kuasar-wasm.service

wasm: add kuasar-wasm systemd service

wasm: add kuasar-wasm systemd service

---

vmm/sandbox/config_clh.toml
vmm/sandbox/src/cloud_hypervisor/config.rs

add task config to cloud hypervisor
1. hypervisor.task.debug default false

vmm: add task config to cloud hypervisor

---

.github/workflows/release.yaml
Makefile
scripts/build/build-containerd.sh
scripts/build/cargo-vendor.sh
vmm/scripts/image/centos/build_rootfs.sh
vmm/scripts/kernel/cloud_hypervisor/build.sh

add workflows release

---

vmm/sandbox/src/stratovirt/config.rs
vmm/sandbox/src/stratovirt/devices/block.rs
vmm/sandbox/src/stratovirt/devices/mod.rs
vmm/sandbox/src/stratovirt/devices/rng.rs
vmm/sandbox/src/stratovirt/devices/serial.rs
vmm/sandbox/src/stratovirt/devices/vhost_user_fs.rs
vmm/sandbox/src/stratovirt/devices/vsock.rs
vmm/sandbox/src/stratovirt/factory.rs
vmm/sandbox/src/stratovirt/mod.rs

vmm-sandboxer support starting stratovirt lightweight vm sandbox, which uses lightweight microvm mainboard and mmio bus.

vmm: support starting stratovirt lightweight vm sandbox

---

vmm/sandbox/src/stratovirt/devices/virtio_net.rs
vmm/sandbox/src/stratovirt/mod.rs

net device bus and addr should not be set, transport should be mmio when starting stratovirt lightweight vm sandbox

vmm:fix stratovirt lightweight vm sandbox start failed when cni enabled

---

vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/client.rs
vmm/sandbox/src/cloud_hypervisor/devices/mod.rs
vmm/sandbox/src/cloud_hypervisor/devices/vfio.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/network/link.rs
vmm/sandbox/src/network/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/utils.rs

1. Support VFIO device in vmm.
2. Run libc::connect() in spawn_blocking to avoid blocking other task.
3. Return OK() if sandbox is in CREATED state.
4. Return io error in cmd pre_exec

vmm: support VFIO device

---

vmm/sandbox/Cargo.lock
vmm/sandbox/Cargo.toml
vmm/sandbox/build.rs
vmm/sandbox/src/args.rs
vmm/sandbox/src/bin/cloud_hypervisor/main.rs
vmm/sandbox/src/bin/qemu/main.rs
vmm/sandbox/src/bin/stratovirt/main.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/lib.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/version.rs

1. Modify the args parsing method of Kuasar VMM: use clap to parse args in the args.rs file, and replace the usage of args in load_config.
2. Add build.rs, inject build information using the `built` library during the build process.
3. Add a function to print version information and build information in args.rs.
``` zsh
➜  sandbox git:(tzh-version) ✗ ./target/debug/cloud_hypervisor  --help    
Usage: cloud_hypervisor [OPTIONS]
Options:
-v, --version        Version info
-c, --config <FILE>  Config file path, only for cloud hypervisor and stratovirt
-d, --dir <DIR>      Sandboxer working directory
-l, --listen <FILE>  Address for sandboxer\'s server
-h, --help           Print help
➜  sandbox git:(tzh-version) ✗ # before commit
➜  sandbox git:(tzh-version) ✗ ./target/debug/cloud_hypervisor …
```

vmm: add version info

---

vmm/scripts/image/build_image.sh

In the [v0.5.0 release workflow:](https://github.com/kuasar-io/kuasar/actions/runs/7528597290/job/20511976902) , it failed with building vmm image as `apt-get install` met 404 error. Should update repo before install any packages.
Here is the result on my personal repo: https://github.com/Burning1020/kuasar/actions/runs/7536124247/job/20513086311

build: Update repo before installation

---

vmm/sandbox/Cargo.lock
vmm/task/Cargo.lock
vmm/task/src/container.rs
vmm/task/src/io.rs

1. report more OCI runtime errors
2. delete pid file of exec process
3. implement `close_io`

task: some bugfixs

---

Makefile
vmm/sandbox/Cargo.lock
vmm/sandbox/config_clh.toml
vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/network/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/storage/mod.rs
vmm/sandbox/src/utils.rs
vmm/scripts/image/centos/build.sh
vmm/scripts/image/centos/build_rootfs.sh
vmm/task/Cargo.lock
vmm/task/src/main.rs

According to the debug experience, make some change to print log. Follow up: https://github.com/kuasar-io/rust-extensions/pull/28

Change some log printing

---

.github/workflows/ci.yml
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/devices/block.rs
vmm/sandbox/src/stratovirt/devices/rng.rs
vmm/sandbox/src/utils.rs

fix #115
reason: The result of the cargo test command includes some compilation warnings that need to be cleaned.

[vmm]: fix cargo test compilation warnings

---

vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/client.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs

Add sleep in the loop of connceting `UnixStream`, to prevent tokio task from trapping in poll recursively.

sandbox: bugfix infinite loop in new_ttrpc_client()

---

vmm/common/src/lib.rs
vmm/sandbox/src/cgroup.rs
vmm/sandbox/src/sandbox.rs
vmm/task/src/main.rs

Since the sandbox was deleted more than twice, the sandbox dir should already be removed in the first time. Thus, should ignore not found error in the following delation.
Signed-off-by: Zhang Tianyang <burning9699@gmail.com>

sandbox: Ignore not found error in sandbox deletion

---

vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/network/link.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/vm.rs

Optimize sandbox lifecycle management
1. Add many roll back handlers in the process of starting sandbox.
2. Move setup network to Start sandbox as it should be called near the vm startup.
3. Only monit running sandbox and dump it status in time.
4. Sandbox stop should make sure the sandbox is stopped successfully, so wait it
to stop for 10s.
5. If the VM process terminated suddenly and the containerd has no idea to stop
sandbox, destroy network should be done in monit thread.
6. Forcefully kill vmm process in stopping sandbox.
Signed-off-by: Zhang Tianyang <burning9699@gmail.com>

network: fix private sandbox netns

---

vmm/sandbox/src/cgroup.rs
vmm/sandbox/src/sandbox.rs

Use a default sandbox cgroup path("kuasar-vmm") if not present. 
This is useful to avoid staining root cgroup path.

cgroup: use default sandbox cgroup path

---

vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/device.rs
vmm/sandbox/src/network/link.rs
vmm/sandbox/src/qemu/devices/vsock.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/devices/vsock.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/utils.rs

1. `/dev/tun` was opened but not closed in time after spawning vmm process.
2. Close socket fd in time after getting bdf for eth interface.
3. Shutdown sync_clock thread when sandbox was stopped.
Signed-off-by: Zhang Tianyang <burning9699@gmail.com>

bugfix: residual sync clock thread

---

Makefile
vmm/scripts/image/build.sh
vmm/scripts/image/centos/binaries.list
vmm/scripts/image/centos/build_rootfs.sh
vmm/scripts/image/centos/rpm.list

1. add some command binaries for debug in vm
2. build.sh is for docker/ctr/isula to prepare guest rootfs and build it to image or initrd, thus it should not have any difference with each guest os.

build: add some commands and make build.sh independent

---

vmm/scripts/kernel/cloud_hypervisor/build.sh

Remove redundant linux kernel build steps. Refer to: [Building your Kernel](https://www.cloudhypervisor.org/docs/prologue/quick-start/#building-your-kernel)

[bugfix]delete redundant 'make'

---

vmm/sandbox/Cargo.lock
vmm/sandbox/src/args.rs
vmm/sandbox/src/bin/cloud_hypervisor/main.rs
vmm/sandbox/src/bin/qemu/main.rs
vmm/sandbox/src/bin/stratovirt/main.rs
vmm/sandbox/src/cloud_hypervisor/hooks.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/config.rs
vmm/sandbox/src/container/handler/append.rs
vmm/sandbox/src/container/handler/mod.rs
vmm/sandbox/src/container/handler/mount.rs
vmm/sandbox/src/lib.rs
vmm/sandbox/src/qemu/config.rs
vmm/sandbox/src/qemu/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/storage/mod.rs
vmm/sandbox/src/stratovirt/mod.rs
vmm/sandbox/src/vm.rs

Follow up: https://github.com/kuasar-io/rust-extensions/pull/30
The origional flags were parsed by both vmm-sandboxer and containerd-sandbox, which is arguly. I refactor this logic, paas the `listening_addr` and `working_dir` to run a sandboxer instance.
Considering practical uses, I al;so add a new flag `log_levl` in commandline for debuging.

refactor: refactor flag parser

---

README.md

Move license scan badge up to the others.

doc: update license scan badge

---

vmm/sandbox/src/storage/mod.rs
vmm/sandbox/src/storage/mount.rs

When the mounted hostpath is tmpfs or when mounting a secret, the container cannot access the data. These two types of mounts are tmpfs, and due to memory isolation between the host and the virtual machine, the virtual machine will reallocate tmpfs, resulting in empty data. 
Fix:Except for empty dir allocated by memory, all other tmpfs are bind-mounted into the virtual machine.

vmm: fix tmpfs bind dir empty

---

vmm/scripts/image/build.sh
vmm/scripts/image/centos/binaries.list
vmm/scripts/image/centos/build_rootfs.sh
vmm/scripts/image/centos/rpm.list

Update guest image to fedora:40 since CentOS7 was already EOS on July 2024.

building: update guest image to fedora:40

---

README.md

This part has been moved to new web page.

Docs: Update installation URL of WasmEdge

---

vmm/common/build.rs
vmm/sandbox/build.rs
vmm/sandbox/src/cgroup.rs
vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/config.rs
vmm/sandbox/src/device.rs
vmm/sandbox/src/lib.rs
vmm/sandbox/src/network/convert.rs
vmm/sandbox/src/network/link.rs
vmm/sandbox/src/network/route.rs
vmm/sandbox/src/qemu/config.rs
vmm/sandbox/src/qemu/mod.rs
vmm/scripts/image/build_image.sh
vmm/scripts/image/centos/build_rootfs.sh
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/container.rs
vmm/task/src/main.rs
vmm/task/src/netlink.rs
vmm/task/src/sandbox_service.rs
vmm/task/src/task.rs

This pull request addresses several Clippy warnings and improves overall code formatting. The changes include:
1. Replace `Default::default()` with specific struct's `default()` method where applicable.
2. Remove usage of `expect()` function to improve error handling.
3. Modify wildcard imports (`*`) to be more specific.
4. Remove `set -x` from shell scripts to reduce verbosity.
Additionally, the entire codebase has been reformatted using `rustfmt` for consistency.
These changes aim to improve code quality, readability, and adherence to Rust best practices. No functional changes have been made to the software.
Please review and let me know if any further modifications are needed.

vmm: fix clippy warning

---

vmm/task/src/main.rs

Ttrpc Server in task would be closed after start_task_server() as Rust will drop the variable, so extra it to keep it alive as long as main funtion.

task: bugfix for ttrpc server closed

---

vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/debug.rs
vmm/task/src/io.rs
vmm/task/src/main.rs
vmm/task/src/netlink.rs
vmm/task/src/stream.rs

After https://github.com/kuasar-io/rust-extensions/pull/31, nix was bumped to 0.28.0 and should also bump it in vmm/task.

build(deps): bump nix from 0.25.0 to 0.28.0 in /vmm/task

---

.github/workflows/ci.yml

cargo-deny [0.16.0](https://github.com/EmbarkStudios/cargo-deny/releases) has changed a lot, use legacy 0.15.1 to check.

ci: use legacy 0.15.1 cargo-deny

---

wasm/Cargo.lock
wasm/Cargo.toml
wasm/build.rs
wasm/src/args.rs
wasm/src/main.rs
wasm/src/sandbox.rs
wasm/src/version.rs

1. Add version info and refactor flag parser, follow up #110 
2. Support the new sandbox controller api

wasm: support new sandbox controller api and flag parser

---

vmm/common/src/lib.rs
vmm/sandbox/src/cloud_hypervisor/factory.rs
vmm/sandbox/src/container/handler/ns.rs
vmm/sandbox/src/sandbox.rs
vmm/task/src/config.rs
vmm/task/src/debug.rs
vmm/task/src/main.rs

Before starting the virtual machine, pay attention to the NamespaceMode setting of pid namespace in PodSandboxConfig. If it is set to "Pod", add task.share_pidns to the startup parameters of Kuasar's task.
When the task starts and detects the share_pidns parameter, create a pid ns when creating the shared namespace.
Since the pid ns needs to take effect on child processes, two forks are required. The process forked executes the pause function and does not exit anymore.

sandbox: support shared process namespace

---

docs/containerd.md
docs/vmm/how-to-run-kuasar-with-isulad-and-stratovirt.md
examples/run_example_container.sh
examples/run_example_wasm_container.sh
scripts/build/build-containerd.sh

1. Update container runtime with prefix "kuasar", e.g. "kuasar-vmm", "kuasar-wasm"
2. Update containerd to v0.2.0-kuasar tag since we have a set of new APIs.

doc: update container runtime with prefix kuasar

---

vmm/common/build.rs
vmm/common/src/api/mod.rs
vmm/common/src/protos/github.com/containerd/containerd/api/services/ttrpc/events/v1/events.proto
vmm/common/src/protos/github.com/containerd/containerd/protobuf/plugin/fieldpath.proto
vmm/common/src/protos/google/protobuf/any.proto
vmm/common/src/protos/google/protobuf/descriptor.proto
vmm/common/src/protos/google/protobuf/timestamp.proto
vmm/common/src/protos/sandbox.proto
vmm/sandbox/src/client.rs
vmm/sandbox/src/sandbox.rs
vmm/task/src/main.rs
vmm/task/src/sandbox_service.rs
vmm/task/src/task.rs

Sandboxer calls get_event() in task while task monitors the oom cgroup to generate events, then the event will be passed to sandboxer as well as contaienrd. Eventually, the get_event() continues to wait for the next event.

vmm: feat: support OOM report to containerd

---

vmm/common/Cargo.toml
vmm/common/build.rs
vmm/common/src/api/mod.rs
vmm/common/src/protos/containerd/types/transfer/data.proto
vmm/common/src/protos/google/protobuf/any.proto
vmm/common/src/protos/streaming.proto
vmm/sandbox/Cargo.lock
vmm/sandbox/Cargo.toml
vmm/sandbox/src/cloud_hypervisor/hooks.rs
vmm/sandbox/src/container/handler/io.rs
vmm/sandbox/src/qemu/hooks.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/stratovirt/hooks.rs
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/container.rs
vmm/task/src/io.rs
vmm/task/src/main.rs
vmm/task/src/streaming.rs

containerd 2.0 sandbox controller api has changed, kuasar should adopt it.
containerd support io by streaming api, make kuasar vmm support it.

vmm: support new sandbox controller api and streaming io

---

vmm/task/src/main.rs

**Description:** 
This PR sets the Linux sysctl defaults for our server configuration. The changes added:
-  /proc/sys/vm/overcommit_memory
- Set overcommit_memory to 1, allowing the kernel to overcommit memory, allocate more memory than is physically available
- /proc/sys/net/ipv4/vs/expire_nodest_conn
- Enable automatic expiration of nodest connections
These changes aim to improve the performance  of our server. Please review and let me know if you have any questions or concerns.

Set Linux sysctl defaults for vm configuration

---

vmm/common/Cargo.toml
vmm/common/src/protos/sandbox.proto
vmm/sandbox/Cargo.lock
vmm/sandbox/src/client.rs
vmm/sandbox/src/cloud_hypervisor/factory.rs
vmm/sandbox/src/sandbox.rs
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/config.rs
vmm/task/src/main.rs
vmm/task/src/sandbox.rs
vmm/task/src/sandbox_service.rs

This PR adds support for configuring pod sysctl settings in the VMM (Virtual Machine Manager) component of our Kubernetes runtime project.
With this change, users can now specify custom sysctl settings for their pods, allowing for more fine-grained control over the runtime environment. This feature is particularly useful for workloads that require specific kernel parameter settings.
The implementation includes the necessary changes to the VMM codebase to parse and apply sysctl settings from the pod's configuration.

vmm: support pod sysctl configuration

---

vmm/sandbox/src/network/convert.rs
vmm/sandbox/src/network/mod.rs
vmm/sandbox/src/network/route.rs

This commit adds support for IPv6 networking in pods. Specifically, it updates the
container runtime to allow pods to be assigned IPv6 addresses.

vmm: add IPv6 support for pod networking

---

vmm/task/src/sandbox_service.rs

Support exec request into vm for debuging. We shoule also provide a CLI with this capbililies in the future.

task: support exec into vm

---

vmm/sandbox/config_clh.toml
vmm/sandbox/src/cloud_hypervisor/config.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs

The current log output of virtiofsd is to stdout/stderr collected by its parents process vmm-sandboxer.
As a result, it will be lost if sandboxer process restarts. Redirecting virtiofsd log to syslog could make it persistent.
Virtiofsd already supports `--syslog` option: https://gitlab.com/virtio-fs/virtiofsd/-/merge_requests/61

vmm: redirect virtiofsd log to syslog

---

runc/Cargo.lock
runc/Cargo.toml
runc/build.rs
runc/rustfmt.toml
runc/src/args.rs
runc/src/common.rs
runc/src/main.rs
runc/src/runc.rs
runc/src/sandbox.rs
runc/src/task.rs
runc/src/version.rs

runc: support new sandbox api

---

vmm/common/src/protos/sandbox.proto
vmm/sandbox/Cargo.lock
vmm/sandbox/Cargo.toml
vmm/sandbox/src/network/address.rs
vmm/sandbox/src/network/convert.rs
vmm/sandbox/src/network/link.rs
vmm/sandbox/src/network/netlink.rs
vmm/sandbox/src/network/route.rs
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/netlink.rs

CNI added the network route under pod namespace, in the vmm case, kuasar should sync the route of host OS to guest OS as well as flags of route, e.g. `onlink`.

vmm: Sync route flags

---

vmm/scripts/image/build_image.sh
vmm/task/src/main.rs

1. ignore not exist kernel param when init vm
2. withdraw partition mode to gpt, it seemd that our kernel doesn't support msdos

task: ignore not exist kernel param

---

rust-toolchain.toml
vmm/task/src/streaming.rs

The CI occasionally fails due to updates in some lint rules, so we set **MSRV**(Minimum Supported Rust Version) to Rust 1.74 in order to pass it.

ci: add MSRV

---

README.md

The runtime names registered in containered have changed after Kuasar https://github.com/kuasar-io/kuasar/releases/tag/v1.0.0.

add prefix `kuasar-` for container runtime

---

vmm/sandbox/src/qemu/config.rs

vmm:qemu support aarch64

---

rust-toolchain.toml
vmm/common/Cargo.toml
vmm/common/src/lib.rs
vmm/common/src/signal.rs
vmm/common/src/trace.rs
vmm/sandbox/Cargo.lock
vmm/sandbox/Cargo.toml
vmm/sandbox/config_clh.toml
vmm/sandbox/config_stratovirt_aarch64.toml
vmm/sandbox/config_stratovirt_x86_64.toml
vmm/sandbox/src/bin/cloud_hypervisor/main.rs
vmm/sandbox/src/bin/qemu/main.rs
vmm/sandbox/src/bin/stratovirt/main.rs
vmm/sandbox/src/cloud_hypervisor/config.rs
vmm/sandbox/src/cloud_hypervisor/mod.rs
vmm/sandbox/src/config.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/utils.rs
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/config.rs
vmm/task/src/container.rs
vmm/task/src/main.rs

closes #5
https://github.com/kuasar-io/kuasar/blob/08cfdc8d93d33f5e216276cbc74f9dcf89aeb569/vmm/sandbox/src/sandbox.rs#L342
- Visualize the results:
1. Enable tracing feature:
```toml
[sandbox]
enable_tracing = true
[hypervisor]
[hypervisor.task]
enable_tracing = true
[hypervisor.virtiofsd]
```
2. Run the jaeger server:
```bash
docker run --rm --name jaeger \
-p 6831:6831/udp \
-p 6832:6832/udp \
-p 5778:5778 \
-p 16686:16686 \
-p 4317:4317 \
-p 4318:4318 \
-p 14250:14250 \
-p 14268:14268 \
-p 14269:14269 \
-p 9411:9411 \
jaegertracing/all-in-one
```
3. Run the Kuasar: https://github.com/kuasar-io/kuasar#quick-start
4. Check the result: visit the web page http://localhost:16686/
The following API will be instrumented:
1. **Sandbox API**
```rust
pub trait Sandboxer {
type Sandbox: Sandbox …
```

vmm: imporve observability to vmm-task & vmm-sandboxer

---

Makefile
vmm/common/src/lib.rs
vmm/task/Cargo.lock
vmm/task/Cargo.toml
vmm/task/src/container.rs
vmm/task/src/debug.rs
vmm/task/src/io.rs
vmm/task/src/main.rs
vmm/task/src/task.rs
vmm/task/src/youki.rs

Kuasar can create lightweight Virtual Machine (VMM) type Pods and containers within the virtual machines. Currently, the VMM-task process inside the VM invokes the runc command to create containers, which incurs some performance overhead. Youki [containers/youki: A container runtime written in Rust](https://github.com/containers/youki) is a container runtime written in Rust and also follows the OCI specification. The goal is to use Youki to improve container creation speed and reduce performance overhead.
Currently everything is supported except for the stdio without tty, we will submit another PR to fix it after https://github.com/youki-dev/youki/pull/2961 is merged.

Apply youki to create containers.

---

Makefile
vmm/sandbox/config_qemu_aarch64.toml
vmm/sandbox/config_qemu_x86_64.toml
vmm/sandbox/src/args.rs
vmm/sandbox/src/bin/qemu/main.rs
vmm/sandbox/src/qemu/config.rs

vmm:qemu support config_qemu.toml

vmm:qemu support config_qemu.toml

---

docs/wasm/How-to-run-Llama-3-8B-with-Kubernetes.md

doc: Update llamaedge app docs

---

.github/workflows/ci.yml
runc/src/sandbox.rs
rust-toolchain.toml
vmm/common/build.rs

update rust to 1.81 to support newest cargo-deny and clear clippy warning.

ci: update rust to 1.81

---

vmm/sandbox/src/container/handler/spec.rs

When the kubelet configures cpuManagerPolicy as static, the Pod will specify CPU IDs for CPU affinity. Due to the different cpusets of the guest OS and host OS, this can lead to configuration failures. There is no need for CPU affinity in the guest OS, so the Pod's cpuset should be cleared.

clear pod cpuset to support "cpuManagerPolicy=static"

---

vmm/sandbox/src/network/link.rs

The tap name must be less than 16 bytes, including the '\0' terminator. The prefix "tap_kuasar_" is too long, which affects the index size. When the index exceeds 9999, the tap name becomes invalid. Therefore, shorten the tap name prefix to "tap_kua_".

Shorten tap name

---

vmm/sandbox/src/bin/cloud_hypervisor/main.rs
vmm/sandbox/src/bin/stratovirt/main.rs

When first start on a node, kuasar-vmm will fail because the work dir is not created, so we first determin if the dir exist and then call the recover.

vmm: fix recover failed when first start

---

MAINTAINERS.md

Xuepeng Xu(@xukobe) has been actively contributing to Kuasar project and has delivered many public speeches about Kuasar. I propose Xuepeng Xu as a maintainer.
Vote from maintainers: 6 LGTM required (1/2 of 12)
+ Nominee confirmation

MAINTAINERS: add Xuepeng Xu as maintainer

---

.github/workflows/release.yaml
Makefile
vmm/scripts/kernel/cloud_hypervisor/build.sh

This PR addresses two key improvements to our build and release processes:
1. Updates the release workflow to use the latest version of the upload-artifact GitHub Action (v4)
2. Adapts our kernel compilation process to be compatible with the latest version of cloud-hypervisor
These changes ensure our release pipeline remains reliable and compatible with our current dependencies.
- Verified that artifacts are correctly uploaded in the release workflow: [release workflow test](https://github.com/morningtzh/kuasar/actions/runs/13968515602)
- Tested kernel compilation with the latest cloud-hypervisor version
- Confirmed that the generated kernel works as expected in our environment
This PR addresses ongoing maintenance needs and does not correspond to a specific issue.

Fix Release Workflow and Update Kernel Compilation

---

.github/workflows/release.yaml
Makefile
vmm/scripts/kernel/cloud_hypervisor/build.sh

This PR addresses two key improvements to our build and release processes:
1. Updates the release workflow to use the latest version of the upload-artifact GitHub Action (v4)
2. Adapts our kernel compilation process to be compatible with the latest version of cloud-hypervisor
These changes ensure our release pipeline remains reliable and compatible with our current dependencies.
- Verified that artifacts are correctly uploaded in the release workflow: [release workflow test](https://github.com/morningtzh/kuasar/actions/runs/13968515602)
- Tested kernel compilation with the latest cloud-hypervisor version
- Confirmed that the generated kernel works as expected in our environment
This PR addresses ongoing maintenance needs and does not correspond to a specific issue.

[release/1.0]Fix Release Workflow and Update Kernel Compilation

---

quark/src/sandbox.rs
runc/src/sandbox.rs
rust-toolchain.toml
vmm/sandbox/src/network/mod.rs
vmm/sandbox/src/sandbox.rs
vmm/sandbox/src/utils.rs
wasm/src/sandbox.rs

update rust to 1.81 to support newest cargo-deny and clear clippy warning.

ci:updata rust to 1.85
