kuasar-io/kuasar

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/cleanup.yml
- .github/ISSUE_TEMPLATE/feature-request.yml
Fix #2:  add three issue templates for create an issue(Bug Report, Cleanup and Feature Request).
> Add issue template

- .github/workflows/ci.yml
- README.md
> CI: Fix wasmedge to v0.11.2

- Makefile
- vmm/scripts/image/build_image.sh
1. remove double quotes from ifeq in Makefile
2. fix wrong path for stratovirt installation
3. add -P for losetup for partition scan
4. fix os_distro name for openEuler
> Fix couple issues in Makefile and build scripts

- vmm/scripts/image/centos/build.sh
Add isulad as container engine for image build
> Add isulad support for vmm-image build

- vmm/sandbox/src/sandbox.rs
Optimize the process of sandboxes lock when deleting sandbox.
> Sandbox: Optimize sandboxes lock when deleting

- examples/run_example_wasm_container.sh
Update wasm container example script
> Example: Update wasm container example script

- docs/containerd.md
Provides important information regarding the recommended Go version.
> Update Containerd doc

- vmm/sandbox/config_stratovirt.toml
- vmm/sandbox/src/stratovirt/config.rs
- vmm/sandbox/src/vm.rs
Support enable memory prealloc using stratovirt as hypervisor
> Support stratovirt memory prealloc

- vmm/sandbox/Cargo.toml
Should use the "async" feature of containerd-shim for async sandboxer
> Update vmm/sandbox Cargo.toml

- examples/run_example_container.sh
- examples/run_example_wasm_container.sh
> docs: Update examples script

- ROADMAP.md
> doc: update roadmap

- MAINTAINERS.md
> doc: add maintainers

- ADOPTERS.md
> doc: add adopters

- MAINTAINERS.md
Add Michael Yuan and JingXiao Lu to Maintainers
> doc: Update Maintainers

- README.md
Update Readme:
- slack link
- Performance link
> doc: Update slack link in Readme

- vmm/task/src/main.rs
Fix vmm high CPU usage after started a container, which caused by dead loop of waitpid.
StillAlived returned when the waitpid syscall return 0, which means there is no more events so we should break the loop.
> vmm-task:break the loop of waitpid when StillAlive returned

- vmm/sandbox/Cargo.lock
- vmm/sandbox/src/client.rs
- vmm/sandbox/src/cloud_hypervisor/hooks.rs
- vmm/sandbox/src/qemu/hooks.rs
- vmm/sandbox/src/sandbox.rs
- vmm/sandbox/src/stratovirt/hooks.rs
- vmm/task/Cargo.lock
- vmm/task/src/sandbox_service.rs
Introduce a set of management mechanism based on Precision Time Protocol to keep guest time synchronized(<=10ms) with host for every 60 seconds.
> vmm: support time synchronization

- vmm/sandbox/src/cloud_hypervisor/mod.rs
- vmm/sandbox/src/qemu/mod.rs
- vmm/sandbox/src/sandbox.rs
- vmm/sandbox/src/stratovirt/mod.rs
- vmm/sandbox/src/vm.rs
Add vcpu thread of cloud hypervisor process to sandbox vcpu cgroup.
This is not include virtiofsd child process if have.
> vmm: add vcpus of clh to sandbox cgroup

- CODEOWNERS
- MAINTAINERS.md
Add CODEOWNERS for code ownership of maintaienrs.
> doc: add CODEOWNERS

- tests/benchmark/scripts/boot-parallel-kata-time.sh
- tests/benchmark/scripts/boot-parallel-kuasar-time.sh
- tests/benchmark/scripts/boot-serial-kata-time.sh
- tests/benchmark/scripts/boot-serial-kuasar-time.sh
- tests/benchmark/scripts/kata-mem-test.sh
- tests/benchmark/scripts/kuasar-mem-test.sh
The indentation format of the comment is incorrect.
Signed-off-by: FreeCarbene <1718658837@qq.com>
> [benchmark] format tests scripts' comment

- vmm/sandbox/src/cgroup.rs
- vmm/sandbox/src/stratovirt/qmp.rs
- wasm/src/utils.rs
- wasm/src/wasmtime.rs
add copyright for:
1. vmm/sandbox/src/cgroup.rs
2. vmm/sandbox/src/stratovirt/qmp.rs
3. wasm/src/utils.rs
4. wasm/src/wasmtime.rs
> add kuasar copyright

- runc/src/sandbox.rs
- vmm/sandbox/src/sandbox.rs
> clippy: truncate with sandbox.json file

- Makefile
Need to add prerequisites to Makefile targets to ensure that after modifying the source files, 'make' can compile without prompting 'is up to date'.
> add targets to .PHONY

- vmm/common/src/lib.rs
- vmm/task/src/main.rs
Fix unshared network ns as it should be shared with host in vmm container and update name of network namespace to "network"
> network: fix private sandbox netns

- vmm/sandbox/Cargo.lock
- vmm/task/Cargo.lock
Update to latest: https://github.com/kuasar-io/rust-extensions/pull/29
> build(deps): bump rust-extensions to latest@5f2edcff in /vmm

- docs/containerd.md
- docs/vmm/how-to-run-kuasar-with-isulad-and-stratovirt.md
- scripts/build/build-containerd.sh
Update containerd config to version 3
> containerd: Update containerd config to version 3

- .github/workflows/ci.yml
- docs/wasm/How-to-run-Llama-3-8B-with-Kubernetes.md
- wasm/src/wasmedge.rs
Add support of `wasi_nn` plugin with preload LLM, a markdown is also added.
> wasm: feat: support wasm_nn with llm application

- vmm/sandbox/src/container/handler/storage.rs
- vmm/sandbox/src/storage/mod.rs
- vmm/sandbox/src/storage/utils.rs
Support readonly option of volume
> vmm: support readonly option of volume

- docs/vmm/README.md
- quark/Cargo.lock
- runc/Cargo.lock
- shim/Cargo.lock
- vmm/sandbox/Cargo.lock
- vmm/sandbox/src/bin/cloud_hypervisor/main.rs
- vmm/sandbox/src/bin/stratovirt/main.rs
- vmm/sandbox/src/container/handler/spec.rs
- vmm/sandbox/src/network/link.rs
- vmm/scripts/image/build.sh
- vmm/task/Cargo.lock
- vmm/task/src/config.rs
- vmm/task/src/debug.rs
- vmm/task/src/main.rs
- wasm/Cargo.lock
This PR merges the latest bug fixes from the main branch into the release/1.0 branch. This integration is essential for ensuring that the release/1.0 branch includes all recent improvements and corrections, paving the way for the upcoming bugfix release version 1.0.1. By consolidating these changes, we aim to enhance the stability and performance of the release, providing our users with a more reliable experience.
Fix some security alerts.
> [release/1.0] Prepare release for v1.0.1

- Makefile
- vmm/sandbox/Cargo.toml
- vmm/sandbox/config_qemu_virtcca_aarch64.toml
- vmm/sandbox/src/qemu/config.rs
- vmm/sandbox/src/qemu/devices/block.rs
- vmm/sandbox/src/qemu/devices/scsi.rs
- vmm/sandbox/src/qemu/devices/serial.rs
- vmm/sandbox/src/qemu/devices/virtio_9p.rs
- vmm/sandbox/src/qemu/devices/virtio_net.rs
- vmm/sandbox/src/qemu/devices/vsock.rs
> vmm: qemu support virtcca

- docs/vmm/how-to-run-kuasar-with-qemu.md
add how-to-run-kuasar-with-qemu.md
> docs：add how-to-run-kuasar-with-qemu.md in /docs/vmm
